export const MAX_OCCUPANCY = {
  "Ocean Deluxe": [
    { adults: 2, children: 0, toddlers: 0, infants: 1 },
    { adults: 1, children: 0, toddlers: 0, infants: 0 },
    { adults: 1, children: 0, toddlers: 0, infants: 1 },
    { adults: 1, children: 1, toddlers: 0, infants: 0 },
    { adults: 1, children: 0, toddlers: 1, infants: 0 },
    { adults: 1, children: 1, toddlers: 0, infants: 1 },
    { adults: 1, children: 0, toddlers: 1, infants: 1 },
    { adults: 2, children: 0, toddlers: 0, infants: 0 },
  ],

  "Family Room": [
    { adults: 5, children: 0, toddlers: 0, infants: 1 },
    { adults: 1, children: 0, toddlers: 0, infants: 0 },
    { adults: 1, children: 1, toddlers: 0, infants: 0 },
    { adults: 1, children: 0, toddlers: 1, infants: 0 },
    { adults: 1, children: 0, toddlers: 0, infants: 1 },
    { adults: 1, children: 1, toddlers: 0, infants: 1 },
    { adults: 1, children: 0, toddlers: 1, infants: 1 },
    { adults: 2, children: 0, toddlers: 0, infants: 0 },
    { adults: 2, children: 1, toddlers: 0, infants: 0 },
    { adults: 2, children: 0, toddlers: 1, infants: 0 },
    { adults: 2, children: 0, toddlers: 0, infants: 1 },
    { adults: 2, children: 1, toddlers: 0, infants: 1 },
    { adults: 2, children: 0, toddlers: 1, infants: 1 },
    { adults: 2, children: 1, toddlers: 1, infants: 0 },
    { adults: 3, children: 0, toddlers: 0, infants: 0 },
    { adults: 3, children: 1, toddlers: 0, infants: 0 },
    { adults: 3, children: 0, toddlers: 1, infants: 0 },
    { adults: 3, children: 0, toddlers: 0, infants: 1 },
    { adults: 3, children: 1, toddlers: 0, infants: 1 },
    { adults: 3, children: 1, toddlers: 1, infants: 0 },
    { adults: 3, children: 2, toddlers: 0, infants: 1 },
    { adults: 2, children: 2, toddlers: 0, infants: 1 },
    { adults: 2, children: 2, toddlers: 0, infants: 0 },
    { adults: 3, children: 2, toddlers: 0, infants: 0 },
    { adults: 4, children: 0, toddlers: 0, infants: 0 },
    { adults: 4, children: 1, toddlers: 0, infants: 0 },
    { adults: 4, children: 0, toddlers: 0, infants: 1 },
    { adults: 4, children: 1, toddlers: 1, infants: 0 },
    { adults: 4, children: 1, toddlers: 0, infants: 1 },
    { adults: 4, children: 0, toddlers: 1, infants: 1 },
    { adults: 5, children: 0, toddlers: 0, infants: 0 },
  ],

  "Family Cabins": [
    { adults: 5, children: 0, toddlers: 0, infants: 1 },
    { adults: 1, children: 0, toddlers: 0, infants: 0 },
    { adults: 1, children: 1, toddlers: 0, infants: 0 },
    { adults: 1, children: 0, toddlers: 1, infants: 0 },
    { adults: 1, children: 0, toddlers: 0, infants: 1 },
    { adults: 1, children: 1, toddlers: 0, infants: 1 },
    { adults: 1, children: 0, toddlers: 1, infants: 1 },
    { adults: 2, children: 0, toddlers: 0, infants: 0 },
    { adults: 2, children: 1, toddlers: 0, infants: 0 },
    { adults: 2, children: 0, toddlers: 1, infants: 0 },
    { adults: 2, children: 0, toddlers: 0, infants: 1 },
    { adults: 2, children: 1, toddlers: 0, infants: 1 },
    { adults: 3, children: 0, toddlers: 0, infants: 0 },
    { adults: 3, children: 1, toddlers: 0, infants: 0 },
    { adults: 3, children: 2, toddlers: 0, infants: 1 },
    { adults: 2, children: 2, toddlers: 0, infants: 1 },
    { adults: 2, children: 2, toddlers: 0, infants: 0 },
    { adults: 3, children: 2, toddlers: 0, infants: 0 },
    { adults: 4, children: 0, toddlers: 0, infants: 0 },
    { adults: 4, children: 1, toddlers: 0, infants: 0 },
    { adults: 4, children: 0, toddlers: 1, infants: 0 },
    { adults: 4, children: 0, toddlers: 0, infants: 1 },
    { adults: 5, children: 0, toddlers: 0, infants: 0 },
    { adults: 5, children: 1, toddlers: 0, infants: 0 },
  ],

  Studios: [
    { adults: 4, children: 0, toddlers: 0, infants: 2 },
    { adults: 1, children: 0, toddlers: 0, infants: 0 },
    { adults: 1, children: 1, toddlers: 0, infants: 0 },
    { adults: 1, children: 0, toddlers: 1, infants: 0 },
    { adults: 1, children: 0, toddlers: 0, infants: 1 },
    { adults: 1, children: 1, toddlers: 0, infants: 1 },
    { adults: 1, children: 0, toddlers: 1, infants: 1 },
    { adults: 1, children: 2, toddlers: 0, infants: 0 },
    { adults: 1, children: 0, toddlers: 2, infants: 0 },
    { adults: 2, children: 0, toddlers: 0, infants: 0 },
    { adults: 2, children: 1, toddlers: 0, infants: 0 },
    { adults: 2, children: 0, toddlers: 1, infants: 0 },
    { adults: 2, children: 0, toddlers: 0, infants: 1 },
    { adults: 2, children: 1, toddlers: 0, infants: 1 },
    { adults: 2, children: 0, toddlers: 1, infants: 1 },
    { adults: 3, children: 0, toddlers: 0, infants: 0 },
    { adults: 3, children: 1, toddlers: 0, infants: 0 },
    { adults: 3, children: 0, toddlers: 1, infants: 0 },
    { adults: 3, children: 0, toddlers: 0, infants: 1 },
    { adults: 3, children: 1, toddlers: 0, infants: 1 },
    { adults: 2, children: 2, toddlers: 0, infants: 1 },
    { adults: 3, children: 1, toddlers: 0, infants: 1 },
    { adults: 4, children: 0, toddlers: 0, infants: 1 },
    { adults: 4, children: 0, toddlers: 0, infants: 0 },
    { adults: 4, children: 0, toddlers: 0, infants: 0 },
    { adults: 4, children: 1, toddlers: 0, infants: 0 },
    { adults: 4, children: 0, toddlers: 1, infants: 0 },
    { adults: 4, children: 0, toddlers: 0, infants: 1 },
  ],

  "Villa (Sunrise)": [
    { adults: 5, children: 0, toddlers: 0, infants: 1 },
    { adults: 1, children: 0, toddlers: 0, infants: 0 },
    { adults: 1, children: 1, toddlers: 0, infants: 0 },
    { adults: 1, children: 0, toddlers: 1, infants: 0 },
    { adults: 1, children: 0, toddlers: 0, infants: 1 },
    { adults: 1, children: 1, toddlers: 0, infants: 1 },
    { adults: 1, children: 0, toddlers: 1, infants: 1 },
    { adults: 2, children: 0, toddlers: 0, infants: 0 },
    { adults: 2, children: 1, toddlers: 0, infants: 0 },
    { adults: 2, children: 0, toddlers: 1, infants: 0 },
    { adults: 2, children: 0, toddlers: 0, infants: 1 },
    { adults: 2, children: 1, toddlers: 0, infants: 1 },
    { adults: 3, children: 0, toddlers: 0, infants: 0 },
    { adults: 3, children: 1, toddlers: 0, infants: 0 },
    { adults: 3, children: 0, toddlers: 1, infants: 0 },
    { adults: 3, children: 0, toddlers: 0, infants: 1 },
    { adults: 4, children: 0, toddlers: 0, infants: 0 },
    { adults: 4, children: 1, toddlers: 0, infants: 0 },
    { adults: 4, children: 0, toddlers: 1, infants: 0 },
    { adults: 4, children: 0, toddlers: 0, infants: 1 },
    { adults: 5, children: 0, toddlers: 0, infants: 0 },
  ],
  "Villa (Sunset)": [
    { adults: 5, children: 0, toddlers: 0, infants: 1 },
    { adults: 1, children: 0, toddlers: 0, infants: 0 },
    { adults: 1, children: 1, toddlers: 0, infants: 0 },
    { adults: 1, children: 0, toddlers: 1, infants: 0 },
    { adults: 1, children: 0, toddlers: 0, infants: 1 },
    { adults: 1, children: 1, toddlers: 0, infants: 1 },
    { adults: 1, children: 0, toddlers: 1, infants: 1 },
    { adults: 2, children: 0, toddlers: 0, infants: 0 },
    { adults: 2, children: 1, toddlers: 0, infants: 0 },
    { adults: 2, children: 0, toddlers: 1, infants: 0 },
    { adults: 2, children: 0, toddlers: 0, infants: 1 },
    { adults: 2, children: 1, toddlers: 0, infants: 1 },
    { adults: 3, children: 0, toddlers: 0, infants: 0 },
    { adults: 3, children: 1, toddlers: 0, infants: 0 },
    { adults: 3, children: 0, toddlers: 1, infants: 0 },
    { adults: 3, children: 0, toddlers: 0, infants: 1 },
    { adults: 4, children: 0, toddlers: 0, infants: 0 },
    { adults: 4, children: 1, toddlers: 0, infants: 0 },
    { adults: 4, children: 0, toddlers: 1, infants: 0 },
    { adults: 4, children: 0, toddlers: 0, infants: 1 },
    { adults: 5, children: 0, toddlers: 0, infants: 0 },
  ],

  "Family Deluxe (The Loft)": [
    { adults: 5, children: 0, toddlers: 0, infants: 1 },
    { adults: 1, children: 0, toddlers: 0, infants: 0 },
    { adults: 1, children: 1, toddlers: 0, infants: 0 },
    { adults: 1, children: 0, toddlers: 1, infants: 0 },
    { adults: 1, children: 0, toddlers: 0, infants: 1 },
    { adults: 1, children: 1, toddlers: 0, infants: 1 },
    { adults: 1, children: 0, toddlers: 1, infants: 1 },
    { adults: 2, children: 0, toddlers: 0, infants: 0 },
    { adults: 2, children: 1, toddlers: 0, infants: 0 },
    { adults: 2, children: 0, toddlers: 1, infants: 0 },
    { adults: 2, children: 0, toddlers: 0, infants: 1 },
    { adults: 2, children: 1, toddlers: 0, infants: 1 },
    { adults: 3, children: 0, toddlers: 0, infants: 0 },
    { adults: 3, children: 1, toddlers: 0, infants: 0 },
    { adults: 3, children: 0, toddlers: 1, infants: 0 },
    { adults: 3, children: 0, toddlers: 0, infants: 1 },
    { adults: 3, children: 2, toddlers: 0, infants: 1 },
    { adults: 2, children: 2, toddlers: 0, infants: 1 },
    { adults: 2, children: 2, toddlers: 0, infants: 0 },
    { adults: 3, children: 2, toddlers: 0, infants: 0 },
    { adults: 4, children: 0, toddlers: 0, infants: 0 },
    { adults: 4, children: 1, toddlers: 0, infants: 0 },
    { adults: 4, children: 0, toddlers: 1, infants: 0 },
    { adults: 4, children: 0, toddlers: 0, infants: 1 },
    { adults: 5, children: 0, toddlers: 0, infants: 0 },
  ],
};
