name: Deploy React App

on:
  push:
    branches:
      - ci

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Setup SSH Agent
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATEKEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
    
    - name: Deploy to server
      run: |
        scp -i ~/.ssh/id_rsa -r dist/* $SSH_USER@$SSH_HOST:/var/www/html/